/**
 * Course blueprints.
 *
 * Every title, subtitle and section spine here is original, written for this
 * project. Nothing is scraped from or paraphrased out of any real platform's
 * catalogue — the resemblance is to how technical subjects are *taught*, which
 * is not anyone's property.
 *
 * A blueprint is deliberately small: a title, who it is for, and the spine of
 * sections it moves through. `generate.ts` expands that into the full course —
 * lessons, durations, pricing, ratings — deterministically, so the same
 * blueprint always produces the same course.
 */

export interface Blueprint {
  /** Course title. Unique across the catalogue; the slug derives from it. */
  title: string;
  /** Category slug. */
  category: string;
  level: "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "ALL_LEVELS";
  /** One line that says who it is for and what changes. */
  subtitle: string;
  /** Section titles, in order. Four to eight; the generator uses them as-is. */
  spine: string[];
  tags: string[];

  /**
   * Real-world overrides.
   *
   * The generator normally derives artwork, price and popularity
   * deterministically from the slug — see the header note in `generate.ts`.
   * A course migrated in from an external source (a client's own catalogue,
   * a real partner course) carries real values for some of those fields, and
   * a generated placeholder would misrepresent it. Setting an override here
   * takes that field out of the deterministic generator for this course only;
   * every field left unset still behaves exactly as it did before.
   */
  /** A real photograph/URL, in place of the generated SVG illustration. */
  thumbnailUrl?: string;
  /** Real sale price, in paise. */
  priceAmountOverride?: number;
  /** Real strike-through price, in paise, or null for "not discounted". */
  compareAtAmountOverride?: number | null;
  /** Real published rating (e.g. from the source catalogue), 0-5. */
  ratingAvgOverride?: number;
  /** Real enrolment/learner count. */
  enrollmentCountOverride?: number;
}

export const BLUEPRINTS: Blueprint[] = [
  /* ===================== PROGRAMMING ===================== */
  {
    title: "Python for Practical Automation",
    category: "programming",
    level: "BEGINNER",
    subtitle: "Replace the repetitive parts of your week with scripts you actually trust.",
    spine: [
      "Getting Python to do something useful",
      "Files, folders and formats",
      "Talking to the web",
      "Handling failure without hiding it",
      "Scheduling and packaging your scripts",
    ],
    tags: ["python", "productivity", "testing"],
  },
  {
    title: "Full Stack TypeScript Engineering",
    category: "programming",
    level: "INTERMEDIATE",
    subtitle:
      "One language from the database to the browser, and the type safety to make it worthwhile.",
    spine: [
      "Why one language end to end",
      "Modelling your domain in types",
      "Typed data access",
      "Sharing contracts across the boundary",
      "Errors that the compiler catches",
      "Testing a typed stack",
      "Shipping and versioning",
    ],
    tags: ["typescript", "nodejs", "api-design", "testing"],
  },
  {
    title: "Refactoring Legacy Code Without Fear",
    category: "programming",
    level: "INTERMEDIATE",
    subtitle: "Change code you did not write and do not fully understand, safely.",
    spine: [
      "Reading unfamiliar code",
      "Characterisation tests",
      "Seams and safe extraction",
      "Breaking dependencies",
      "Incremental rewrites",
      "Knowing when to stop",
    ],
    tags: ["testing", "architecture", "documentation"],
  },
  {
    title: "Concurrency Patterns in Go",
    category: "programming",
    level: "ADVANCED",
    subtitle: "Goroutines, channels and the failure modes nobody warns you about.",
    spine: [
      "The concurrency model",
      "Channels as a design tool",
      "Context and cancellation",
      "Synchronisation primitives",
      "Detecting races",
      "Patterns for real workloads",
    ],
    tags: ["concurrency", "performance", "architecture"],
  },
  {
    title: "Rust for Systems Programmers",
    category: "programming",
    level: "ADVANCED",
    subtitle: "Ownership, borrowing and writing fast code the compiler will vouch for.",
    spine: [
      "Ownership and moves",
      "Borrowing and lifetimes",
      "Traits and generics",
      "Error handling",
      "Unsafe and when it is warranted",
      "Concurrency without data races",
    ],
    tags: ["performance", "concurrency", "algorithms"],
  },
  {
    title: "Clean Architecture in Practice",
    category: "programming",
    level: "INTERMEDIATE",
    subtitle: "Boundaries that survive a change of framework, database or team.",
    spine: [
      "What a boundary buys you",
      "Entities and use cases",
      "Adapters and ports",
      "Dependency direction",
      "Testing across layers",
      "When layering costs more than it saves",
    ],
    tags: ["architecture", "testing", "documentation"],
  },
  {
    title: "Writing Code Reviews People Act On",
    category: "programming",
    level: "ALL_LEVELS",
    subtitle: "Reviews that improve the code and the author, not just the diff.",
    spine: [
      "What review is for",
      "Reading a diff well",
      "Comments that land",
      "Disagreeing productively",
      "Reviewing as a junior",
      "Team norms and throughput",
    ],
    tags: ["communication", "documentation", "leadership"],
  },
  {
    title: "Object-Oriented Design in Java",
    category: "programming",
    level: "BEGINNER",
    subtitle: "Classes, interfaces and composition, taught through problems that need them.",
    spine: [
      "Objects as responsibilities",
      "Interfaces and polymorphism",
      "Composition over inheritance",
      "Collections and generics",
      "Exceptions and resource safety",
      "Designing a small system",
    ],
    tags: ["algorithms", "architecture", "testing"],
  },
  {
    title: "Test-Driven Development That Sticks",
    category: "programming",
    level: "INTERMEDIATE",
    subtitle: "The discipline, the pitfalls, and the tests worth keeping.",
    spine: [
      "Red, green, refactor",
      "What to test and what not to",
      "Test doubles honestly used",
      "Designing for testability",
      "Legacy code and TDD",
      "Suites that stay fast",
    ],
    tags: ["testing", "architecture", "performance"],
  },

  /* ===================== WEB DEVELOPMENT ===================== */
  {
    title: "Modern React Application Architecture",
    category: "web-development",
    level: "INTERMEDIATE",
    subtitle: "Component boundaries, data flow and state that does not fight you at scale.",
    spine: [
      "Rendering and reconciliation",
      "Component boundaries",
      "State that belongs where it is used",
      "Server data and caching",
      "Routing and code splitting",
      "Performance profiling",
      "Testing a React codebase",
    ],
    tags: ["react", "typescript", "performance", "testing"],
  },
  {
    title: "CSS Layout From First Principles",
    category: "web-development",
    level: "BEGINNER",
    subtitle: "Flexbox, grid and the box model explained so layouts stop surprising you.",
    spine: [
      "The box model, properly",
      "Normal flow and positioning",
      "Flexbox",
      "Grid",
      "Responsive without breakpointsoup",
      "Debugging a broken layout",
    ],
    tags: ["accessibility", "typography", "design-systems"],
  },
  {
    title: "Web Performance for Real Users",
    category: "web-development",
    level: "INTERMEDIATE",
    subtitle: "Measure what users feel, then fix the things that actually move it.",
    spine: [
      "What to measure and why",
      "The critical rendering path",
      "Images and fonts",
      "JavaScript cost",
      "Caching and delivery",
      "Keeping performance from regressing",
    ],
    tags: ["performance", "caching", "analytics"],
  },
  {
    title: "Accessible Interfaces by Default",
    category: "web-development",
    level: "ALL_LEVELS",
    subtitle: "Build interfaces that work with a keyboard, a screen reader and a bad connection.",
    spine: [
      "Who is excluded and how",
      "Semantic HTML first",
      "Keyboard and focus",
      "ARIA when HTML is not enough",
      "Colour, contrast and motion",
      "Testing with real assistive tech",
    ],
    tags: ["accessibility", "testing", "design-systems"],
  },
  {
    title: "API Design for Front-End Teams",
    category: "web-development",
    level: "INTERMEDIATE",
    subtitle: "Ask for the right endpoints, and recognise the ones that will hurt later.",
    spine: [
      "What makes an API pleasant",
      "REST conventions worth keeping",
      "GraphQL trade-offs",
      "Pagination, filtering and sorting",
      "Errors and status codes",
      "Versioning and deprecation",
    ],
    tags: ["api-design", "rest", "graphql", "documentation"],
  },
  {
    title: "Progressive Web Apps That Work Offline",
    category: "web-development",
    level: "ADVANCED",
    subtitle: "Service workers, storage and syncing without losing the user's work.",
    spine: [
      "The offline problem",
      "Service worker lifecycle",
      "Caching strategies",
      "IndexedDB and structured storage",
      "Background sync and conflicts",
      "Installability and updates",
    ],
    tags: ["caching", "performance", "reliability"],
  },
  {
    title: "Server-Side Rendering and Streaming",
    category: "web-development",
    level: "ADVANCED",
    subtitle: "Hydration, streaming and the trade-offs behind every rendering strategy.",
    spine: [
      "Rendering strategies compared",
      "Hydration and its costs",
      "Streaming and suspense",
      "Data fetching on the server",
      "Caching layers",
      "Measuring the result",
    ],
    tags: ["react", "performance", "caching"],
  },
  {
    title: "Building Design Systems in Code",
    category: "web-development",
    level: "INTERMEDIATE",
    subtitle: "Tokens, components and the governance that stops a system rotting.",
    spine: [
      "What a system is for",
      "Design tokens",
      "Component API design",
      "Documentation that gets read",
      "Versioning and adoption",
      "Measuring whether it worked",
    ],
    tags: ["design-systems", "tokens", "documentation", "accessibility"],
  },
  {
    title: "Node.js Services in Production",
    category: "web-development",
    level: "INTERMEDIATE",
    subtitle: "The event loop, back-pressure and running Node where it actually matters.",
    spine: [
      "The event loop, concretely",
      "Streams and back-pressure",
      "Structuring a service",
      "Configuration and secrets",
      "Observability",
      "Deploying and scaling",
    ],
    tags: ["nodejs", "observability", "reliability", "performance"],
  },

  /* ===================== DATA SCIENCE ===================== */
  {
    title: "Python for Practical Data Analysis",
    category: "data-science",
    level: "BEGINNER",
    subtitle: "Load messy data, clean it honestly and answer a question with it.",
    spine: [
      "Data frames and the mental model",
      "Loading and inspecting real data",
      "Cleaning without lying",
      "Grouping and aggregation",
      "Joining datasets",
      "Communicating a finding",
    ],
    tags: ["python", "pandas", "analysis", "visualisation"],
  },
  {
    title: "Statistics for People Who Ship",
    category: "data-science",
    level: "BEGINNER",
    subtitle: "Enough statistics to avoid the mistakes that cost real decisions.",
    spine: [
      "Variation and uncertainty",
      "Sampling and what it costs",
      "Confidence intervals",
      "Hypothesis tests and their limits",
      "Common traps",
      "Reporting a result",
    ],
    tags: ["statistics", "analysis", "experimentation"],
  },
  {
    title: "Designing Experiments That Answer Something",
    category: "data-science",
    level: "INTERMEDIATE",
    subtitle: "A/B tests from hypothesis to decision, including when not to run one.",
    spine: [
      "What an experiment can and cannot tell you",
      "Metrics and guardrails",
      "Power and duration",
      "Randomisation and interference",
      "Reading results honestly",
      "Decisions and follow-ups",
    ],
    tags: ["experimentation", "statistics", "analytics"],
  },
  {
    title: "Data Visualisation for Decisions",
    category: "data-science",
    level: "ALL_LEVELS",
    subtitle: "Charts that carry a point rather than decorate a slide.",
    spine: [
      "What the chart is for",
      "Choosing a form",
      "Colour and encoding",
      "Annotation and hierarchy",
      "Dashboards that get used",
      "Charts that mislead",
    ],
    tags: ["visualisation", "analysis", "communication"],
  },
  {
    title: "Time Series Forecasting in Practice",
    category: "data-science",
    level: "INTERMEDIATE",
    subtitle: "Seasonality, drift and forecasts a business can plan against.",
    spine: [
      "What makes time series different",
      "Decomposition and seasonality",
      "Baselines that are hard to beat",
      "Classical models",
      "Evaluation and backtesting",
      "Putting a forecast into production",
    ],
    tags: ["forecasting", "statistics", "python"],
  },
  {
    title: "Feature Engineering for Tabular Data",
    category: "data-science",
    level: "INTERMEDIATE",
    subtitle: "The part of modelling that usually decides the outcome.",
    spine: [
      "Where signal actually lives",
      "Numeric transformations",
      "Categorical encoding",
      "Time-aware features",
      "Leakage and how to spot it",
      "Feature selection",
    ],
    tags: ["pandas", "evaluation", "analysis"],
  },
  {
    title: "SQL Analytics for Business Intelligence",
    category: "data-science",
    level: "BEGINNER",
    subtitle: "Answer real business questions with queries you can defend.",
    spine: [
      "Thinking in sets",
      "Joins that do what you meant",
      "Aggregation and window functions",
      "Cohorts and funnels",
      "Query performance",
      "Turning a query into a report",
    ],
    tags: ["sql", "analytics", "databases"],
  },
  {
    title: "Building Reliable Data Pipelines",
    category: "data-science",
    level: "ADVANCED",
    subtitle: "Ingestion, orchestration and pipelines that fail loudly instead of quietly.",
    spine: [
      "Pipeline shapes",
      "Idempotency and replay",
      "Orchestration",
      "Data quality checks",
      "Schema evolution",
      "Monitoring and alerting",
    ],
    tags: ["reliability", "observability", "databases"],
  },

  /* ===================== ARTIFICIAL INTELLIGENCE ===================== */
  {
    title: "Evaluating Language Model Applications",
    category: "artificial-intelligence",
    level: "ADVANCED",
    subtitle: "Build the evaluation harness before you build the feature.",
    spine: [
      "Why demos mislead",
      "Defining a task precisely",
      "Building an evaluation set",
      "Automatic and human scoring",
      "Regression testing prompts",
      "Deciding whether to ship",
    ],
    tags: ["llms", "evaluation", "prompt-design"],
  },
  {
    title: "Prompt Design as an Engineering Discipline",
    category: "artificial-intelligence",
    level: "INTERMEDIATE",
    subtitle: "Prompts you can version, test and hand to somebody else.",
    spine: [
      "What the model is actually doing",
      "Structure and instruction",
      "Examples and their cost",
      "Controlling format",
      "Failure modes",
      "Versioning and testing prompts",
    ],
    tags: ["prompt-design", "llms", "evaluation"],
  },
  {
    title: "Retrieval-Augmented Generation End to End",
    category: "artificial-intelligence",
    level: "ADVANCED",
    subtitle: "Chunking, embedding, retrieval and the honest limits of the pattern.",
    spine: [
      "When retrieval helps",
      "Chunking strategies",
      "Embeddings and vector stores",
      "Ranking and reranking",
      "Grounding and citations",
      "Evaluating a RAG system",
    ],
    tags: ["llms", "nlp", "evaluation", "caching"],
  },
  {
    title: "Building AI Features Users Trust",
    category: "artificial-intelligence",
    level: "INTERMEDIATE",
    subtitle: "Uncertainty, guardrails and interfaces that admit what the model does not know.",
    spine: [
      "Where trust breaks",
      "Designing for uncertainty",
      "Guardrails and refusals",
      "Human review loops",
      "Latency and streaming",
      "Measuring trust",
    ],
    tags: ["llms", "evaluation", "ux-research"],
  },
  {
    title: "Natural Language Processing Foundations",
    category: "artificial-intelligence",
    level: "BEGINNER",
    subtitle: "Tokenisation, embeddings and the ideas underneath modern language models.",
    spine: [
      "Text as data",
      "Tokenisation",
      "Representations and embeddings",
      "Classification tasks",
      "Sequence models",
      "Where transformers changed things",
    ],
    tags: ["nlp", "deep-learning", "python"],
  },
  {
    title: "Fine-Tuning Small Models Effectively",
    category: "artificial-intelligence",
    level: "ADVANCED",
    subtitle: "When fine-tuning beats prompting, and how to do it without wasting a budget.",
    spine: [
      "Fine-tune or prompt",
      "Dataset construction",
      "Parameter-efficient methods",
      "Training runs and monitoring",
      "Evaluating the result",
      "Serving a tuned model",
    ],
    tags: ["fine-tuning", "llms", "mlops", "evaluation"],
  },
  {
    title: "Computer Vision for Applied Problems",
    category: "artificial-intelligence",
    level: "INTERMEDIATE",
    subtitle: "Classification, detection and getting a vision model into a product.",
    spine: [
      "Images as tensors",
      "Convolutional intuition",
      "Transfer learning",
      "Detection and segmentation",
      "Data augmentation",
      "Deployment constraints",
    ],
    tags: ["computer-vision", "deep-learning", "python"],
  },

  /* ===================== MACHINE LEARNING ===================== */
  {
    title: "Machine Learning Model Deployment",
    category: "machine-learning",
    level: "ADVANCED",
    subtitle: "The gap between a notebook and a service that survives a Monday.",
    spine: [
      "What deployment actually changes",
      "Packaging a model",
      "Serving patterns",
      "Monitoring and drift",
      "Retraining pipelines",
      "Rollback and safety",
    ],
    tags: ["mlops", "reliability", "observability"],
  },
  {
    title: "Supervised Learning Fundamentals",
    category: "machine-learning",
    level: "BEGINNER",
    subtitle: "Regression, classification and knowing when a model is fooling you.",
    spine: [
      "The learning problem",
      "Linear models",
      "Trees and ensembles",
      "Overfitting and regularisation",
      "Evaluation metrics",
      "Building a first pipeline",
    ],
    tags: ["python", "statistics", "evaluation"],
  },
  {
    title: "Deep Learning Without the Hand-Waving",
    category: "machine-learning",
    level: "INTERMEDIATE",
    subtitle: "Backpropagation, architectures and what training actually does.",
    spine: [
      "From linear models to networks",
      "Backpropagation by hand",
      "Optimisers and schedules",
      "Regularisation",
      "Architectures and why they differ",
      "Debugging a training run",
    ],
    tags: ["deep-learning", "python", "performance"],
  },
  {
    title: "Model Evaluation and Error Analysis",
    category: "machine-learning",
    level: "INTERMEDIATE",
    subtitle: "Metrics lie in specific ways. Learn which, and what to look at instead.",
    spine: [
      "Choosing a metric",
      "Baselines that matter",
      "Slicing and subgroup analysis",
      "Calibration",
      "Error analysis workflow",
      "Reporting results honestly",
    ],
    tags: ["evaluation", "statistics", "analysis"],
  },
  {
    title: "Recommendation Systems in Production",
    category: "machine-learning",
    level: "ADVANCED",
    subtitle: "Candidate generation, ranking and the feedback loops that distort both.",
    spine: [
      "The recommendation problem",
      "Collaborative filtering",
      "Content and hybrid approaches",
      "Ranking and re-ranking",
      "Cold start",
      "Feedback loops and bias",
    ],
    tags: ["evaluation", "mlops", "experimentation"],
  },
  {
    title: "MLOps Foundations",
    category: "machine-learning",
    level: "INTERMEDIATE",
    subtitle: "Reproducibility, lineage and pipelines that another engineer can run.",
    spine: [
      "Reproducibility as a requirement",
      "Experiment tracking",
      "Feature stores",
      "CI for models",
      "Deployment and rollback",
      "Cost and capacity",
    ],
    tags: ["mlops", "ci-cd", "observability"],
  },

  /* ===================== CYBERSECURITY ===================== */
  {
    title: "Application Security for Developers",
    category: "cybersecurity",
    level: "INTERMEDIATE",
    subtitle: "The vulnerability classes that actually appear in code review.",
    spine: [
      "Thinking like an attacker",
      "Injection and its relatives",
      "Authentication and sessions",
      "Authorization and IDOR",
      "Secrets and configuration",
      "Dependencies and supply chain",
    ],
    tags: ["security", "testing", "api-design"],
  },
  {
    title: "Threat Modelling in an Afternoon",
    category: "cybersecurity",
    level: "ALL_LEVELS",
    subtitle: "A lightweight process that finds real problems before code exists.",
    spine: [
      "What threat modelling is for",
      "Diagramming a system",
      "Identifying threats",
      "Ranking and choosing",
      "Mitigations and trade-offs",
      "Keeping the model alive",
    ],
    tags: ["threat-modelling", "architecture", "risk"],
  },
  {
    title: "Applied Cryptography for Engineers",
    category: "cybersecurity",
    level: "ADVANCED",
    subtitle: "Use the right primitive correctly, and recognise when you should not build it.",
    spine: [
      "What cryptography guarantees",
      "Hashing and password storage",
      "Symmetric encryption",
      "Public key basics",
      "Signatures and tokens",
      "Failure modes and misuse",
    ],
    tags: ["cryptography", "security", "api-design"],
  },
  {
    title: "Incident Response and Postmortems",
    category: "cybersecurity",
    level: "INTERMEDIATE",
    subtitle: "Detect, contain, recover, and learn something that changes behaviour.",
    spine: [
      "Preparing before an incident",
      "Detection and triage",
      "Containment and eradication",
      "Communication during an incident",
      "Blameless postmortems",
      "Turning findings into work",
    ],
    tags: ["incident-response", "observability", "communication"],
  },
  {
    title: "Network Security Fundamentals",
    category: "cybersecurity",
    level: "BEGINNER",
    subtitle: "How traffic moves, where it can be intercepted, and what actually stops that.",
    spine: [
      "The network stack, briefly",
      "TLS and what it proves",
      "Segmentation and firewalls",
      "DNS and its weaknesses",
      "VPNs and zero trust",
      "Monitoring traffic",
    ],
    tags: ["networking", "security", "cryptography"],
  },
  {
    title: "Securing Cloud Workloads",
    category: "cybersecurity",
    level: "ADVANCED",
    subtitle: "Identity, least privilege and the misconfigurations that cause most breaches.",
    spine: [
      "The shared responsibility line",
      "Identity and access management",
      "Network boundaries in cloud",
      "Secrets management",
      "Logging and detection",
      "Compliance without theatre",
    ],
    tags: ["aws", "compliance", "security", "observability"],
  },

  /* ===================== CLOUD COMPUTING ===================== */
  {
    title: "Cloud Infrastructure Fundamentals",
    category: "cloud-computing",
    level: "BEGINNER",
    subtitle: "Compute, storage and networking explained without vendor marketing.",
    spine: [
      "What the cloud actually rents you",
      "Compute options compared",
      "Storage classes and durability",
      "Networking basics",
      "Identity and permissions",
      "Cost from day one",
    ],
    tags: ["aws", "networking", "architecture"],
  },
  {
    title: "Infrastructure as Code with Terraform",
    category: "cloud-computing",
    level: "INTERMEDIATE",
    subtitle: "Declarative infrastructure, state, and changes you can review.",
    spine: [
      "Why declarative",
      "Resources and state",
      "Modules and composition",
      "Plans and reviews",
      "Managing environments",
      "Drift and imports",
    ],
    tags: ["terraform", "ci-cd", "architecture"],
  },
  {
    title: "Designing for Cloud Cost",
    category: "cloud-computing",
    level: "INTERMEDIATE",
    subtitle: "Architecture decisions that show up on the invoice.",
    spine: [
      "Where cloud bills come from",
      "Right-sizing compute",
      "Storage and egress",
      "Managed services trade-offs",
      "Attribution and tagging",
      "Building a cost review habit",
    ],
    tags: ["aws", "architecture", "analytics"],
  },
  {
    title: "Serverless Architecture Patterns",
    category: "cloud-computing",
    level: "INTERMEDIATE",
    subtitle: "Functions, queues and events — and the workloads that suit them.",
    spine: [
      "What serverless changes",
      "Functions and cold starts",
      "Event-driven patterns",
      "State and storage",
      "Observability in serverless",
      "Limits and escape hatches",
    ],
    tags: ["architecture", "observability", "reliability"],
  },
  {
    title: "Multi-Region Systems and Failover",
    category: "cloud-computing",
    level: "ADVANCED",
    subtitle: "Latency, replication and being honest about your recovery objectives.",
    spine: [
      "What multi-region buys",
      "Replication strategies",
      "Consistency trade-offs",
      "Traffic routing",
      "Failover testing",
      "Cost and complexity",
    ],
    tags: ["reliability", "networking", "architecture", "databases"],
  },

  /* ===================== DEVOPS ===================== */
  {
    title: "Continuous Delivery Pipelines",
    category: "devops",
    level: "INTERMEDIATE",
    subtitle: "From commit to production without a release-day ritual.",
    spine: [
      "What CD requires of you",
      "Build and artefact strategy",
      "Test stages that pay off",
      "Deployment strategies",
      "Feature flags",
      "Measuring delivery",
    ],
    tags: ["ci-cd", "testing", "reliability"],
  },
  {
    title: "Kubernetes for Application Teams",
    category: "devops",
    level: "INTERMEDIATE",
    subtitle: "Enough Kubernetes to run your service well, without becoming a platform team.",
    spine: [
      "The objects that matter",
      "Deployments and rollouts",
      "Configuration and secrets",
      "Networking and ingress",
      "Resources and autoscaling",
      "Debugging a broken pod",
    ],
    tags: ["kubernetes", "docker", "observability"],
  },
  {
    title: "Docker and Container Fundamentals",
    category: "devops",
    level: "BEGINNER",
    subtitle: "Images, layers and containers that build the same way twice.",
    spine: [
      "What a container actually is",
      "Images and layers",
      "Writing a good Dockerfile",
      "Volumes and networking",
      "Compose for local work",
      "Registries and security",
    ],
    tags: ["docker", "linux", "ci-cd"],
  },
  {
    title: "Observability Beyond Dashboards",
    category: "devops",
    level: "ADVANCED",
    subtitle: "Logs, metrics and traces that answer questions you did not anticipate.",
    spine: [
      "Monitoring versus observability",
      "Structured logging",
      "Metrics that mean something",
      "Distributed tracing",
      "Alerting without fatigue",
      "Debugging with telemetry",
    ],
    tags: ["observability", "reliability", "performance"],
  },
  {
    title: "Site Reliability Engineering Practices",
    category: "devops",
    level: "ADVANCED",
    subtitle: "Error budgets, toil and running services at a defined level of reliability.",
    spine: [
      "Reliability as a budget",
      "SLIs, SLOs and error budgets",
      "Reducing toil",
      "On-call that people survive",
      "Capacity planning",
      "Change management",
    ],
    tags: ["reliability", "incident-response", "observability"],
  },
  {
    title: "Linux for Engineers Who Deploy",
    category: "devops",
    level: "BEGINNER",
    subtitle: "Processes, permissions and the command line you need on a bad day.",
    spine: [
      "The filesystem and permissions",
      "Processes and signals",
      "Networking from the shell",
      "Logs and systemd",
      "Performance basics",
      "Scripting the routine parts",
    ],
    tags: ["linux", "networking", "performance"],
  },

  /* ===================== DATABASE ===================== */
  {
    title: "PostgreSQL Performance Tuning",
    category: "database",
    level: "ADVANCED",
    subtitle: "Read a query plan, fix the real bottleneck and leave the rest alone.",
    spine: [
      "How the planner thinks",
      "Reading EXPLAIN output",
      "Indexes that get used",
      "Statistics and estimation",
      "Locking and contention",
      "Configuration that matters",
    ],
    tags: ["sql", "performance", "databases", "caching"],
  },
  {
    title: "Data Modelling for Applications",
    category: "database",
    level: "INTERMEDIATE",
    subtitle: "Schemas that make correct code easy and incorrect code hard.",
    spine: [
      "Modelling the domain",
      "Normalisation and when to stop",
      "Keys, constraints and invariants",
      "Modelling change over time",
      "Migrations without downtime",
      "Denormalisation with intent",
    ],
    tags: ["databases", "architecture", "sql"],
  },
  {
    title: "SQL From Query to Optimisation",
    category: "database",
    level: "BEGINNER",
    subtitle: "Write queries that are correct first, then make them fast.",
    spine: [
      "Selecting and filtering",
      "Joins in depth",
      "Aggregation and grouping",
      "Subqueries and CTEs",
      "Window functions",
      "Introduction to performance",
    ],
    tags: ["sql", "databases", "analysis"],
  },
  {
    title: "Transactions, Isolation and Consistency",
    category: "database",
    level: "ADVANCED",
    subtitle: "What your database actually guarantees, and the anomalies it does not prevent.",
    spine: [
      "ACID, precisely",
      "Isolation levels",
      "Anomalies you will meet",
      "Locking and MVCC",
      "Distributed transactions",
      "Designing around the guarantees",
    ],
    tags: ["databases", "concurrency", "reliability"],
  },
  {
    title: "NoSQL Data Stores Compared",
    category: "database",
    level: "INTERMEDIATE",
    subtitle: "Document, key-value, wide-column and graph — and when each earns its place.",
    spine: [
      "Why not relational",
      "Document stores",
      "Key-value and caching",
      "Wide-column stores",
      "Graph databases",
      "Choosing and combining",
    ],
    tags: ["databases", "caching", "architecture"],
  },

  /* ===================== COMPUTER SCIENCE ===================== */
  {
    title: "Data Structures and Algorithms in Java",
    category: "computer-science",
    level: "BEGINNER",
    subtitle: "The structures worth knowing cold, and how to reason about cost.",
    spine: [
      "Complexity and measurement",
      "Arrays, lists and strings",
      "Stacks, queues and heaps",
      "Hash tables",
      "Trees and traversal",
      "Sorting and searching",
      "Graphs",
    ],
    tags: ["algorithms", "data-structures", "performance"],
  },
  {
    title: "Algorithms for Technical Interviews",
    category: "computer-science",
    level: "INTERMEDIATE",
    subtitle: "Pattern recognition, not memorisation — and how to talk while you solve.",
    spine: [
      "What interviews test",
      "Two pointers and sliding windows",
      "Recursion and backtracking",
      "Dynamic programming",
      "Graph traversal",
      "Communicating a solution",
    ],
    tags: ["algorithms", "data-structures", "communication"],
  },
  {
    title: "Operating Systems for Application Engineers",
    category: "computer-science",
    level: "INTERMEDIATE",
    subtitle: "Memory, scheduling and I/O — the layer your performance problems live in.",
    spine: [
      "Processes and threads",
      "Virtual memory",
      "Scheduling",
      "File systems and I/O",
      "System calls",
      "Diagnosing from the OS up",
    ],
    tags: ["operating-systems", "performance", "concurrency"],
  },
  {
    title: "Computer Networks in Practice",
    category: "computer-science",
    level: "BEGINNER",
    subtitle: "What happens between your code and the other machine.",
    spine: [
      "Layers and why they exist",
      "IP and routing",
      "TCP and reliability",
      "DNS",
      "HTTP and TLS",
      "Diagnosing network problems",
    ],
    tags: ["networking", "performance", "security"],
  },
  {
    title: "Compilers and Language Implementation",
    category: "computer-science",
    level: "ADVANCED",
    subtitle: "Build a small language and understand every stage that gets it running.",
    spine: [
      "Lexing",
      "Parsing and grammars",
      "Abstract syntax trees",
      "Semantic analysis",
      "Code generation",
      "Optimisation basics",
    ],
    tags: ["compilers", "algorithms", "performance"],
  },
  {
    title: "Distributed Systems Concepts",
    category: "computer-science",
    level: "ADVANCED",
    subtitle: "Consensus, partitions and the impossibility results worth internalising.",
    spine: [
      "Why distribution is hard",
      "Time and ordering",
      "Replication",
      "Consensus",
      "Partitions and CAP",
      "Designing with failure assumed",
    ],
    tags: ["architecture", "reliability", "concurrency"],
  },

  /* ===================== BUSINESS ===================== */
  {
    title: "Market Positioning for New Products",
    category: "business",
    level: "INTERMEDIATE",
    subtitle: "Decide what you are and who it is for before you spend on channels.",
    spine: [
      "Why tactics fail without positioning",
      "Segmentation that is real",
      "Competitive alternatives",
      "Differentiation you can prove",
      "Messaging that follows",
      "Testing a position",
    ],
    tags: ["positioning", "strategy", "brand"],
  },
  {
    title: "Unit Economics for Operators",
    category: "business",
    level: "INTERMEDIATE",
    subtitle: "Contribution margin, payback and knowing whether growth is worth buying.",
    spine: [
      "What a unit is",
      "Contribution margin",
      "Acquisition cost and payback",
      "Retention and lifetime value",
      "Sensitivity analysis",
      "Making a decision",
    ],
    tags: ["finance-modelling", "analytics", "pricing"],
  },
  {
    title: "Pricing Strategy and Packaging",
    category: "business",
    level: "ADVANCED",
    subtitle: "Value metrics, tiers and the research behind a price change.",
    spine: [
      "Price as a product decision",
      "Choosing a value metric",
      "Packaging and tiers",
      "Research methods",
      "Changing prices safely",
      "Measuring the effect",
    ],
    tags: ["pricing", "positioning", "experimentation"],
  },
  {
    title: "Writing Strategy Documents",
    category: "business",
    level: "ALL_LEVELS",
    subtitle: "Documents that produce a decision instead of another meeting.",
    spine: [
      "What a strategy document does",
      "Framing the problem",
      "Options and trade-offs",
      "Evidence and assumptions",
      "Making a recommendation",
      "Circulating and revising",
    ],
    tags: ["writing", "communication", "strategy"],
  },
  {
    title: "Operations for Small Teams",
    category: "business",
    level: "BEGINNER",
    subtitle: "The processes worth having early, and the ones that are premature.",
    spine: [
      "Process as a tool",
      "Documenting how work happens",
      "Metrics for a small team",
      "Vendors and tooling",
      "Hiring the next person",
      "Scaling what works",
    ],
    tags: ["strategy", "hiring", "documentation"],
  },

  /* ===================== FINANCE ===================== */
  {
    title: "Financial Modelling From a Blank Sheet",
    category: "finance",
    level: "INTERMEDIATE",
    subtitle: "Build a three-statement model somebody else can audit.",
    spine: [
      "Model structure and conventions",
      "Revenue build",
      "Cost and headcount",
      "The three statements linked",
      "Scenarios and sensitivities",
      "Reviewing a model",
    ],
    tags: ["finance-modelling", "accounting", "analysis"],
  },
  {
    title: "Reading Financial Statements",
    category: "finance",
    level: "BEGINNER",
    subtitle: "Income statement, balance sheet and cash flow, and what each conceals.",
    spine: [
      "The three statements",
      "How they connect",
      "Accrual versus cash",
      "Ratios worth computing",
      "Common distortions",
      "Reading a real filing",
    ],
    tags: ["accounting", "analysis", "valuation"],
  },
  {
    title: "Valuation Methods Compared",
    category: "finance",
    level: "ADVANCED",
    subtitle: "DCF, comparables and precedent transactions — with their assumptions exposed.",
    spine: [
      "What valuation is for",
      "Discounted cash flow",
      "Cost of capital",
      "Comparable companies",
      "Precedent transactions",
      "Triangulating a range",
    ],
    tags: ["valuation", "finance-modelling", "analysis"],
  },
  {
    title: "Personal Finance and Investing Basics",
    category: "finance",
    level: "BEGINNER",
    subtitle: "Budgeting, risk and long-horizon investing without the noise.",
    spine: [
      "Cash flow and budgeting",
      "Emergency funds and insurance",
      "Risk and time horizon",
      "Asset classes",
      "Costs, taxes and compounding",
      "Building a simple plan",
    ],
    tags: ["analysis", "risk", "productivity"],
  },

  /* ===================== MARKETING ===================== */
  {
    title: "Analytics for Marketing Decisions",
    category: "marketing",
    level: "INTERMEDIATE",
    subtitle: "Attribution, cohorts and metrics that survive a hard question.",
    spine: [
      "What you can and cannot attribute",
      "Event design",
      "Cohort analysis",
      "Channel measurement",
      "Incrementality",
      "Reporting to a sceptic",
    ],
    tags: ["analytics", "experimentation", "growth"],
  },
  {
    title: "Content Strategy That Compounds",
    category: "marketing",
    level: "BEGINNER",
    subtitle: "Publishing with a thesis, a system and a way to tell whether it worked.",
    spine: [
      "Why most content fails",
      "Audience and intent",
      "Formats and cadence",
      "Distribution",
      "Measurement",
      "Editing and quality control",
    ],
    tags: ["content", "seo", "brand", "writing"],
  },
  {
    title: "Technical SEO Foundations",
    category: "marketing",
    level: "INTERMEDIATE",
    subtitle: "Crawling, indexing and the engineering half of search.",
    spine: [
      "How search engines see a site",
      "Crawling and indexing",
      "Site architecture",
      "Performance and Core Web Vitals",
      "Structured data",
      "Diagnosing a traffic drop",
    ],
    tags: ["seo", "performance", "analytics"],
  },
  {
    title: "Lifecycle and Retention Marketing",
    category: "marketing",
    level: "INTERMEDIATE",
    subtitle: "Onboarding, activation and messaging that earns the next session.",
    spine: [
      "The lifecycle, honestly mapped",
      "Activation",
      "Onboarding sequences",
      "Re-engagement",
      "Churn and win-back",
      "Measuring lifecycle work",
    ],
    tags: ["growth", "analytics", "experimentation"],
  },
  {
    title: "Brand Foundations for Small Companies",
    category: "marketing",
    level: "BEGINNER",
    subtitle: "Voice, identity and consistency without a rebrand budget.",
    spine: [
      "What a brand is and is not",
      "Voice and tone",
      "Visual identity basics",
      "Consistency across surfaces",
      "Brand and product",
      "Evolving a brand",
    ],
    tags: ["brand", "positioning", "content"],
  },

  /* ===================== DESIGN ===================== */
  {
    title: "UI and UX Design Systems",
    category: "design",
    level: "INTERMEDIATE",
    subtitle: "From tokens to components to a system a team will actually adopt.",
    spine: [
      "What a system solves",
      "Foundations and tokens",
      "Component inventory",
      "Patterns and composition",
      "Documentation",
      "Governance and adoption",
    ],
    tags: ["design-systems", "tokens", "accessibility", "documentation"],
  },
  {
    title: "Interface Design Fundamentals",
    category: "design",
    level: "BEGINNER",
    subtitle: "Hierarchy, spacing and typography — the parts that make a screen readable.",
    spine: [
      "Visual hierarchy",
      "Layout and grids",
      "Typography",
      "Colour",
      "Interaction states",
      "Critique and iteration",
    ],
    tags: ["typography", "accessibility", "prototyping"],
  },
  {
    title: "UX Research Methods That Change Decisions",
    category: "design",
    level: "INTERMEDIATE",
    subtitle: "Interviews, usability tests and synthesis that produces a decision.",
    spine: [
      "Choosing a method",
      "Recruiting and screening",
      "Interviewing well",
      "Usability testing",
      "Synthesis",
      "Reporting findings that land",
    ],
    tags: ["ux-research", "communication", "analysis"],
  },
  {
    title: "Prototyping for Product Teams",
    category: "design",
    level: "BEGINNER",
    subtitle: "Fidelity, speed and prototypes that answer a specific question.",
    spine: [
      "What a prototype is for",
      "Choosing fidelity",
      "Interaction and flow",
      "Testing a prototype",
      "Handoff to engineering",
      "Iterating quickly",
    ],
    tags: ["prototyping", "ux-research", "communication"],
  },
  {
    title: "Motion and Micro-Interaction Design",
    category: "design",
    level: "ADVANCED",
    subtitle: "Animation that communicates state rather than decorating a screen.",
    spine: [
      "What motion is for",
      "Timing and easing",
      "Transitions and continuity",
      "Feedback and affordance",
      "Performance",
      "Reduced motion and accessibility",
    ],
    tags: ["accessibility", "performance", "prototyping"],
  },

  /* ===================== PERSONAL DEVELOPMENT ===================== */
  {
    title: "Writing Design Documents That Get Read",
    category: "personal-development",
    level: "ALL_LEVELS",
    subtitle: "Design docs, updates and reviews that get read and acted on.",
    spine: [
      "Why engineers must write",
      "Structure before sentences",
      "Design documents",
      "Status updates",
      "Editing your own work",
      "Writing under disagreement",
    ],
    tags: ["writing", "communication", "documentation"],
  },
  {
    title: "Deep Work for Knowledge Workers",
    category: "personal-development",
    level: "BEGINNER",
    subtitle: "Attention as a resource, and systems that protect it.",
    spine: [
      "Attention and its limits",
      "Designing your day",
      "Managing interruptions",
      "Tooling and notifications",
      "Energy and recovery",
      "Making it stick",
    ],
    tags: ["productivity", "communication"],
  },
  {
    title: "Giving and Receiving Feedback",
    category: "personal-development",
    level: "ALL_LEVELS",
    subtitle: "Conversations that improve work without damaging the relationship.",
    spine: [
      "Why feedback fails",
      "Preparing to give it",
      "Specificity and evidence",
      "Receiving it without defensiveness",
      "Upward feedback",
      "Building a feedback culture",
    ],
    tags: ["communication", "leadership"],
  },
  {
    title: "Technical Interviewing From Both Sides",
    category: "personal-development",
    level: "INTERMEDIATE",
    subtitle: "Preparing as a candidate, and running interviews that predict anything.",
    spine: [
      "What interviews measure",
      "Preparing as a candidate",
      "Structuring your answers",
      "Designing a good interview",
      "Reducing bias",
      "Making a decision",
    ],
    tags: ["hiring", "communication", "algorithms"],
  },
  {
    title: "Negotiation for Technical Professionals",
    category: "personal-development",
    level: "INTERMEDIATE",
    subtitle: "Offers, scope and internal disagreements, handled without antagonism.",
    spine: [
      "Preparation and information",
      "Interests behind positions",
      "Anchoring and framing",
      "Salary conversations",
      "Negotiating scope",
      "Closing well",
    ],
    tags: ["negotiation", "communication", "leadership"],
  },
  {
    title: "Leading Without Authority",
    category: "personal-development",
    level: "INTERMEDIATE",
    subtitle: "Influence, alignment and getting things done across teams you do not run.",
    spine: [
      "Where influence comes from",
      "Building alignment",
      "Running a working group",
      "Managing up",
      "Handling conflict",
      "Sustaining momentum",
    ],
    tags: ["leadership", "communication", "stakeholders"],
  },

  /* ===================== PROJECT MANAGEMENT ===================== */
  {
    title: "Agile Delivery Without the Ceremony",
    category: "project-management",
    level: "INTERMEDIATE",
    subtitle: "The practices that help, separated from the rituals that do not.",
    spine: [
      "What agile was reacting to",
      "Planning and backlogs",
      "Iteration mechanics",
      "Metrics that help",
      "Common failure modes",
      "Adapting the process",
    ],
    tags: ["agile", "estimation", "stakeholders"],
  },
  {
    title: "Estimation and Forecasting for Projects",
    category: "project-management",
    level: "ADVANCED",
    subtitle: "Ranges, reference classes and forecasts you can defend to a stakeholder.",
    spine: [
      "Why estimates are wrong",
      "Reference class forecasting",
      "Ranges and confidence",
      "Decomposition",
      "Tracking and updating",
      "Communicating uncertainty",
    ],
    tags: ["estimation", "risk", "communication"],
  },
  {
    title: "Risk Management in Delivery",
    category: "project-management",
    level: "INTERMEDIATE",
    subtitle: "Identify what could go wrong early enough to do something about it.",
    spine: [
      "What counts as a risk",
      "Identification techniques",
      "Assessment and ranking",
      "Mitigation and contingency",
      "Monitoring",
      "Escalation",
    ],
    tags: ["risk", "stakeholders", "agile"],
  },
  {
    title: "Stakeholder Communication",
    category: "project-management",
    level: "ALL_LEVELS",
    subtitle: "Status, bad news and expectations, handled before they become a crisis.",
    spine: [
      "Mapping stakeholders",
      "Cadence and format",
      "Delivering bad news",
      "Managing expectations",
      "Written updates",
      "Steering meetings",
    ],
    tags: ["stakeholders", "communication", "writing"],
  },
  {
    title: "Running Projects With Remote Teams",
    category: "project-management",
    level: "INTERMEDIATE",
    subtitle: "Asynchronous work, time zones and coordination that does not need a meeting.",
    spine: [
      "What remote changes",
      "Asynchronous by default",
      "Documentation as infrastructure",
      "Meetings worth having",
      "Time zones and handoffs",
      "Team health",
    ],
    tags: ["documentation", "communication", "agile"],
  },

  /* ===================== LANGUAGES ===================== */
  {
    title: "Spanish for Everyday Conversation",
    category: "languages",
    level: "BEGINNER",
    subtitle: "Speak from the first week, with the grammar arriving when you need it.",
    spine: [
      "Sounds and rhythm",
      "Present tense and essentials",
      "Everyday situations",
      "Past tenses",
      "Expressing opinions",
      "Sustaining a conversation",
    ],
    tags: ["vocabulary", "pronunciation", "fluency"],
  },
  {
    title: "Business English for Professionals",
    category: "languages",
    level: "INTERMEDIATE",
    subtitle: "Meetings, email and presentations in clear, confident English.",
    spine: [
      "Register and tone",
      "Email that gets replies",
      "Meetings and interruptions",
      "Presenting",
      "Negotiating language",
      "Writing reports",
    ],
    tags: ["writing", "communication", "vocabulary"],
  },
  {
    title: "Japanese Foundations",
    category: "languages",
    level: "BEGINNER",
    subtitle: "Kana, sentence structure and enough grammar to build on properly.",
    spine: [
      "Hiragana and katakana",
      "Sentence structure",
      "Particles",
      "Verbs and politeness",
      "Numbers and time",
      "Everyday exchanges",
    ],
    tags: ["vocabulary", "grammar", "pronunciation"],
  },
  {
    title: "French Pronunciation and Listening",
    category: "languages",
    level: "INTERMEDIATE",
    subtitle: "Hear what native speakers actually say, and be understood in return.",
    spine: [
      "The sound system",
      "Liaison and elision",
      "Rhythm and intonation",
      "Listening strategies",
      "Common contractions",
      "Shadowing practice",
    ],
    tags: ["pronunciation", "fluency", "vocabulary"],
  },
  {
    title: "German Grammar Made Systematic",
    category: "languages",
    level: "INTERMEDIATE",
    subtitle: "Cases, word order and the patterns that make German predictable.",
    spine: [
      "Cases and why they exist",
      "Articles and adjectives",
      "Word order",
      "Verb forms and tenses",
      "Subordinate clauses",
      "Putting it together",
    ],
    tags: ["grammar", "vocabulary", "fluency"],
  },
];
