import type { Blueprint } from "./blueprints";

/**
 * Second wave of course blueprints.
 *
 * Split across two files purely for readability — a single 160-entry literal is
 * unpleasant to navigate. `generate.ts` concatenates them, and the combined
 * list is checked for duplicate titles and slugs at seed time.
 *
 * As with the first wave, everything here is original.
 */
export const BLUEPRINTS_EXTRA: Blueprint[] = [
  /* ===================== PROGRAMMING ===================== */
  {
    title: "Bash and Shell Scripting in Depth",
    category: "programming",
    level: "INTERMEDIATE",
    subtitle: "Scripts that handle spaces, failures and other people's machines.",
    spine: [
      "The shell as a language",
      "Quoting and expansion",
      "Control flow and functions",
      "Error handling and traps",
      "Text processing tools",
      "Portability and testing",
    ],
    tags: ["linux", "productivity", "testing"],
  },
  {
    title: "C++ for Performance-Critical Code",
    category: "programming",
    level: "ADVANCED",
    subtitle: "Move semantics, templates and getting close to the hardware deliberately.",
    spine: [
      "Value semantics and moves",
      "RAII and resource safety",
      "Templates and generics",
      "The standard library",
      "Memory layout and cache",
      "Profiling and optimisation",
    ],
    tags: ["performance", "concurrency", "algorithms"],
  },
  {
    title: "Functional Programming Concepts",
    category: "programming",
    level: "INTERMEDIATE",
    subtitle: "Immutability, composition and the ideas worth stealing for any language.",
    spine: [
      "Purity and side effects",
      "Higher-order functions",
      "Immutability in practice",
      "Composition and pipelines",
      "Algebraic data types",
      "Applying it in imperative code",
    ],
    tags: ["architecture", "testing", "typescript"],
  },
  {
    title: "Debugging as a Systematic Skill",
    category: "programming",
    level: "ALL_LEVELS",
    subtitle: "Stop guessing. Form hypotheses, bisect, and find the cause.",
    spine: [
      "Why guessing fails",
      "Reproducing reliably",
      "Bisection and elimination",
      "Debuggers and instrumentation",
      "Debugging production",
      "Preventing recurrence",
    ],
    tags: ["testing", "observability", "performance"],
  },

  /* ===================== WEB DEVELOPMENT ===================== */
  {
    title: "Vue.js Application Development",
    category: "web-development",
    level: "BEGINNER",
    subtitle: "Reactivity, components and building a real application from scratch.",
    spine: [
      "Reactivity explained",
      "Components and props",
      "The composition API",
      "Routing",
      "State management",
      "Building and deploying",
    ],
    tags: ["javascript", "testing", "performance"],
  },
  {
    title: "GraphQL API Development",
    category: "web-development",
    level: "INTERMEDIATE",
    subtitle: "Schemas, resolvers and avoiding the N+1 trap in production.",
    spine: [
      "Schema design",
      "Resolvers and data sources",
      "The N+1 problem",
      "Authorization",
      "Caching and persisted queries",
      "Schema evolution",
    ],
    tags: ["graphql", "api-design", "caching", "performance"],
  },
  {
    title: "Web Security for Front-End Engineers",
    category: "web-development",
    level: "INTERMEDIATE",
    subtitle: "XSS, CSRF and CSP explained by the code that gets them wrong.",
    spine: [
      "The browser security model",
      "Cross-site scripting",
      "Content Security Policy",
      "CSRF and same-site cookies",
      "Third-party scripts",
      "Authentication in the browser",
    ],
    tags: ["security", "javascript", "api-design"],
  },
  {
    title: "Testing Web Applications End to End",
    category: "web-development",
    level: "INTERMEDIATE",
    subtitle: "A test pyramid that catches real bugs without a flaky suite.",
    spine: [
      "What to test at each level",
      "Unit and component tests",
      "Integration tests",
      "End-to-end with a real browser",
      "Fighting flakiness",
      "Tests in continuous integration",
    ],
    tags: ["testing", "ci-cd", "reliability"],
  },
  {
    title: "Building a REST API with Django",
    category: "web-development",
    level: "BEGINNER",
    subtitle: "Models, serializers and an API that is documented and tested.",
    spine: [
      "Project structure",
      "Models and migrations",
      "Serializers and views",
      "Authentication",
      "Testing the API",
      "Deploying",
    ],
    tags: ["python", "rest", "api-design", "testing"],
  },

  /* ===================== DATA SCIENCE ===================== */
  {
    title: "Exploratory Data Analysis Done Well",
    category: "data-science",
    level: "BEGINNER",
    subtitle: "Look at data properly before you model it or report on it.",
    spine: [
      "What exploratory analysis is for",
      "Distributions and outliers",
      "Relationships between variables",
      "Missing data",
      "Segment analysis",
      "Writing up what you found",
    ],
    tags: ["pandas", "visualisation", "statistics", "analysis"],
  },
  {
    title: "Causal Inference for Product Analytics",
    category: "data-science",
    level: "ADVANCED",
    subtitle: "Estimate effects when you cannot randomise.",
    spine: [
      "Correlation and its limits",
      "Potential outcomes",
      "Matching and weighting",
      "Difference in differences",
      "Instrumental variables",
      "Communicating causal claims",
    ],
    tags: ["statistics", "experimentation", "analysis"],
  },
  {
    title: "R for Statistical Analysis",
    category: "data-science",
    level: "BEGINNER",
    subtitle: "Tidy data, modelling and reproducible reports.",
    spine: [
      "The tidy data mental model",
      "Reshaping data",
      "Grammar of graphics",
      "Statistical models",
      "Reproducible reports",
      "Sharing your analysis",
    ],
    tags: ["statistics", "visualisation", "analysis"],
  },
  {
    title: "Data Warehousing and Dimensional Modelling",
    category: "data-science",
    level: "INTERMEDIATE",
    subtitle: "Facts, dimensions and a warehouse analysts can actually query.",
    spine: [
      "Why a warehouse",
      "Facts and dimensions",
      "Slowly changing dimensions",
      "Grain and aggregation",
      "Extract, load, transform",
      "Serving analysts",
    ],
    tags: ["sql", "databases", "analytics"],
  },

  /* ===================== ARTIFICIAL INTELLIGENCE ===================== */
  {
    title: "Agentic AI Systems and Tool Use",
    category: "artificial-intelligence",
    level: "ADVANCED",
    subtitle: "Planning, tool calls and keeping an autonomous loop from going wrong.",
    spine: [
      "What an agent is",
      "Tool definitions",
      "Planning and decomposition",
      "State and memory",
      "Failure and recovery",
      "Safety and limits",
    ],
    tags: ["llms", "prompt-design", "evaluation", "reliability"],
  },
  {
    title: "Responsible AI and Model Governance",
    category: "artificial-intelligence",
    level: "INTERMEDIATE",
    subtitle: "Bias, transparency and the documentation a deployed model needs.",
    spine: [
      "Where harm comes from",
      "Measuring bias",
      "Transparency and documentation",
      "Human oversight",
      "Regulation in outline",
      "Building a review process",
    ],
    tags: ["evaluation", "compliance", "risk"],
  },
  {
    title: "Speech and Audio Machine Learning",
    category: "artificial-intelligence",
    level: "ADVANCED",
    subtitle: "Recognition, synthesis and the preprocessing that decides your results.",
    spine: [
      "Audio as data",
      "Feature extraction",
      "Speech recognition",
      "Speaker tasks",
      "Synthesis",
      "Deployment constraints",
    ],
    tags: ["deep-learning", "python", "evaluation"],
  },

  /* ===================== MACHINE LEARNING ===================== */
  {
    title: "Reinforcement Learning Fundamentals",
    category: "machine-learning",
    level: "ADVANCED",
    subtitle: "Rewards, policies and why reinforcement learning is harder than it looks.",
    spine: [
      "The reinforcement learning framing",
      "Markov decision processes",
      "Value methods",
      "Policy gradients",
      "Exploration",
      "When it is the wrong tool",
    ],
    tags: ["deep-learning", "algorithms", "evaluation"],
  },
  {
    title: "Unsupervised Learning and Clustering",
    category: "machine-learning",
    level: "INTERMEDIATE",
    subtitle: "Structure without labels, and how to tell whether you found any.",
    spine: [
      "Learning without labels",
      "Distance and similarity",
      "K-means and variants",
      "Hierarchical clustering",
      "Dimensionality reduction",
      "Validating clusters",
    ],
    tags: ["statistics", "python", "evaluation"],
  },
  {
    title: "Gradient Boosting in Practice",
    category: "machine-learning",
    level: "INTERMEDIATE",
    subtitle: "The family that wins most tabular problems, tuned properly.",
    spine: [
      "Boosting intuition",
      "Trees as weak learners",
      "Hyperparameters that matter",
      "Regularisation and early stopping",
      "Interpreting a model",
      "Serving and monitoring",
    ],
    tags: ["evaluation", "python", "performance"],
  },

  /* ===================== CYBERSECURITY ===================== */
  {
    title: "Security Operations and Detection Engineering",
    category: "cybersecurity",
    level: "ADVANCED",
    subtitle: "Write detections that fire on attacks and stay quiet otherwise.",
    spine: [
      "What a security operations team does",
      "Log sources and coverage",
      "Writing detections",
      "Tuning and false positives",
      "Threat intelligence",
      "Measuring detection quality",
    ],
    tags: ["incident-response", "observability", "security"],
  },
  {
    title: "Penetration Testing Fundamentals",
    category: "cybersecurity",
    level: "INTERMEDIATE",
    subtitle: "Reconnaissance, exploitation and a report somebody can act on.",
    spine: [
      "Scope and authorisation",
      "Reconnaissance",
      "Common web exploits",
      "Privilege escalation",
      "Reporting findings",
      "Retesting and remediation",
    ],
    tags: ["security", "networking", "threat-modelling"],
  },
  {
    title: "Identity and Access Management",
    category: "cybersecurity",
    level: "INTERMEDIATE",
    subtitle: "OAuth, OIDC and single sign-on explained by what each token actually proves.",
    spine: [
      "Authentication versus authorization",
      "OAuth 2 flows",
      "OpenID Connect",
      "Session management",
      "Single sign-on",
      "Common misconfigurations",
    ],
    tags: ["security", "api-design", "cryptography"],
  },

  /* ===================== CLOUD COMPUTING ===================== */
  {
    title: "AWS Core Services in Depth",
    category: "cloud-computing",
    level: "INTERMEDIATE",
    subtitle: "The dozen services most workloads actually use, understood properly.",
    spine: [
      "Accounts and identity",
      "Compute services",
      "Storage and databases",
      "Networking",
      "Queues and events",
      "Monitoring and cost",
    ],
    tags: ["aws", "networking", "observability"],
  },
  {
    title: "Cloud Migration Planning",
    category: "cloud-computing",
    level: "ADVANCED",
    subtitle: "Assess, sequence and migrate without a big-bang cutover.",
    spine: [
      "Assessing a portfolio",
      "Migration strategies",
      "Sequencing and dependencies",
      "Data migration",
      "Cutover and rollback",
      "Post-migration optimisation",
    ],
    tags: ["architecture", "risk", "databases"],
  },
  {
    title: "Edge Computing and Content Delivery",
    category: "cloud-computing",
    level: "INTERMEDIATE",
    subtitle: "Push compute and cache closer to users, and know what breaks.",
    spine: [
      "Why the edge",
      "Content delivery fundamentals",
      "Cache keys and invalidation",
      "Edge functions",
      "Consistency at the edge",
      "Measuring the benefit",
    ],
    tags: ["caching", "performance", "networking"],
  },

  /* ===================== DEVOPS ===================== */
  {
    title: "GitOps and Declarative Delivery",
    category: "devops",
    level: "ADVANCED",
    subtitle: "Git as the source of truth for infrastructure and deployments.",
    spine: [
      "The GitOps premise",
      "Repository structure",
      "Reconciliation loops",
      "Secrets in a Git world",
      "Progressive delivery",
      "Auditing and rollback",
    ],
    tags: ["ci-cd", "kubernetes", "terraform", "compliance"],
  },
  {
    title: "Platform Engineering and Developer Experience",
    category: "devops",
    level: "ADVANCED",
    subtitle: "Build an internal platform teams choose to use rather than route around.",
    spine: [
      "What a platform is for",
      "Golden paths",
      "Self-service infrastructure",
      "Documentation and onboarding",
      "Measuring developer experience",
      "Avoiding platform sprawl",
    ],
    tags: ["documentation", "ci-cd", "observability"],
  },
  {
    title: "Chaos Engineering and Resilience Testing",
    category: "devops",
    level: "ADVANCED",
    subtitle: "Break things deliberately, in daylight, with a hypothesis.",
    spine: [
      "Why inject failure",
      "Steady state and hypotheses",
      "Experiment design",
      "Blast radius control",
      "Running a game day",
      "Turning findings into fixes",
    ],
    tags: ["reliability", "incident-response", "risk"],
  },

  /* ===================== DATABASE ===================== */
  {
    title: "Database Migrations at Scale",
    category: "database",
    level: "ADVANCED",
    subtitle: "Change a schema under live traffic without downtime or data loss.",
    spine: [
      "Why migrations are dangerous",
      "Expand and contract",
      "Backfills",
      "Online schema change tools",
      "Testing a migration",
      "Rollback planning",
    ],
    tags: ["databases", "reliability", "sql"],
  },
  {
    title: "Redis and Caching Patterns",
    category: "database",
    level: "INTERMEDIATE",
    subtitle: "Cache-aside, invalidation and the data structures beyond key-value.",
    spine: [
      "What Redis is good at",
      "Caching strategies",
      "Invalidation",
      "Data structures in Redis",
      "Persistence and durability",
      "Failure modes",
    ],
    tags: ["caching", "performance", "databases"],
  },
  {
    title: "MongoDB Application Patterns",
    category: "database",
    level: "INTERMEDIATE",
    subtitle: "Document modelling, indexing and aggregation for real workloads.",
    spine: [
      "Documents versus rows",
      "Schema design patterns",
      "Indexing",
      "Aggregation pipelines",
      "Transactions and consistency",
      "Scaling and sharding",
    ],
    tags: ["databases", "performance", "architecture"],
  },

  /* ===================== COMPUTER SCIENCE ===================== */
  {
    title: "Discrete Mathematics for Computing",
    category: "computer-science",
    level: "BEGINNER",
    subtitle: "Logic, sets, graphs and counting — the maths that actually recurs.",
    spine: [
      "Logic and proof",
      "Sets and relations",
      "Functions and counting",
      "Graphs",
      "Recursion and induction",
      "Probability basics",
    ],
    tags: ["algorithms", "statistics", "data-structures"],
  },
  {
    title: "Advanced Algorithm Design",
    category: "computer-science",
    level: "ADVANCED",
    subtitle: "Greedy, divide and conquer, and knowing when a problem is genuinely hard.",
    spine: [
      "Design paradigms",
      "Divide and conquer",
      "Greedy algorithms and proofs",
      "Advanced dynamic programming",
      "Network flow",
      "Intractability and approximation",
    ],
    tags: ["algorithms", "data-structures", "performance"],
  },
  {
    title: "Computer Architecture Essentials",
    category: "computer-science",
    level: "INTERMEDIATE",
    subtitle: "Pipelines, caches and why the same code runs at different speeds.",
    spine: [
      "Instructions and execution",
      "Pipelining",
      "Memory hierarchy and caches",
      "Branch prediction",
      "Parallelism",
      "Writing hardware-aware code",
    ],
    tags: ["performance", "operating-systems", "concurrency"],
  },

  /* ===================== BUSINESS ===================== */
  {
    title: "Product Management for Engineers",
    category: "business",
    level: "INTERMEDIATE",
    subtitle: "Discovery, prioritisation and shipping the thing that mattered.",
    spine: [
      "What the role actually is",
      "Discovery and problem framing",
      "Prioritisation",
      "Roadmaps that survive",
      "Working with engineering",
      "Measuring outcomes",
    ],
    tags: ["strategy", "stakeholders", "analytics"],
  },
  {
    title: "Building a Business Case",
    category: "business",
    level: "INTERMEDIATE",
    subtitle: "Numbers, assumptions and a recommendation that withstands scrutiny.",
    spine: [
      "What a business case must answer",
      "Sizing the opportunity",
      "Cost and effort",
      "Risks and alternatives",
      "Sensitivity",
      "Presenting for a decision",
    ],
    tags: ["finance-modelling", "strategy", "writing"],
  },
  {
    title: "Customer Discovery Interviews",
    category: "business",
    level: "BEGINNER",
    subtitle: "Talk to customers in a way that produces evidence rather than encouragement.",
    spine: [
      "Why most interviews fail",
      "Recruiting the right people",
      "Questions that work",
      "Listening and probing",
      "Synthesis",
      "Acting on what you heard",
    ],
    tags: ["ux-research", "positioning", "communication"],
  },

  /* ===================== FINANCE ===================== */
  {
    title: "Corporate Finance Essentials",
    category: "finance",
    level: "INTERMEDIATE",
    subtitle: "Capital structure, cost of capital and investment decisions.",
    spine: [
      "The finance function",
      "Time value of money",
      "Capital budgeting",
      "Capital structure",
      "Working capital",
      "Dividends and buybacks",
    ],
    tags: ["finance-modelling", "valuation", "accounting"],
  },
  {
    title: "Management Accounting for Decisions",
    category: "finance",
    level: "BEGINNER",
    subtitle: "Costing, budgeting and the numbers managers actually use.",
    spine: [
      "Cost behaviour",
      "Costing methods",
      "Break-even and contribution",
      "Budgeting",
      "Variance analysis",
      "Decision-relevant costs",
    ],
    tags: ["accounting", "analysis", "pricing"],
  },
  {
    title: "Risk and Portfolio Theory",
    category: "finance",
    level: "ADVANCED",
    subtitle: "Diversification, correlation and what portfolio theory assumes.",
    spine: [
      "Risk and return",
      "Diversification and correlation",
      "The efficient frontier",
      "Asset pricing models",
      "Factor investing",
      "Assumptions and their limits",
    ],
    tags: ["risk", "valuation", "statistics"],
  },

  /* ===================== MARKETING ===================== */
  {
    title: "Paid Acquisition Fundamentals",
    category: "marketing",
    level: "BEGINNER",
    subtitle: "Campaign structure, creative testing and spending money deliberately.",
    spine: [
      "How ad auctions work",
      "Campaign structure",
      "Creative and messaging",
      "Testing and iteration",
      "Budget and bidding",
      "Measuring return",
    ],
    tags: ["growth", "analytics", "experimentation"],
  },
  {
    title: "Email Marketing and Automation",
    category: "marketing",
    level: "INTERMEDIATE",
    subtitle: "Deliverability, sequences and messages people are glad to receive.",
    spine: [
      "Deliverability basics",
      "List quality and consent",
      "Sequence design",
      "Copy and subject lines",
      "Segmentation",
      "Measuring and iterating",
    ],
    tags: ["content", "growth", "analytics"],
  },
  {
    title: "Marketing for Developer Products",
    category: "marketing",
    level: "ADVANCED",
    subtitle:
      "Reach an audience that distrusts marketing, without pretending you are not doing it.",
    spine: [
      "Why developer audiences differ",
      "Documentation as marketing",
      "Community and advocacy",
      "Content that earns trust",
      "Measuring developer funnels",
      "Common mistakes",
    ],
    tags: ["content", "positioning", "brand"],
  },

  /* ===================== DESIGN ===================== */
  {
    title: "Information Architecture and Navigation",
    category: "design",
    level: "INTERMEDIATE",
    subtitle: "Structure, labels and navigation people can predict.",
    spine: [
      "Structure as a design problem",
      "Card sorting and tree testing",
      "Labelling",
      "Navigation patterns",
      "Search as navigation",
      "Validating a structure",
    ],
    tags: ["ux-research", "accessibility", "prototyping"],
  },
  {
    title: "Data Visualisation Design",
    category: "design",
    level: "INTERMEDIATE",
    subtitle: "Charts as a design surface — encoding, colour and honest emphasis.",
    spine: [
      "Encoding data visually",
      "Choosing chart forms",
      "Colour for data",
      "Layout and annotation",
      "Interactive charts",
      "Charts that mislead",
    ],
    tags: ["visualisation", "accessibility", "typography"],
  },
  {
    title: "Design Critique and Collaboration",
    category: "design",
    level: "ALL_LEVELS",
    subtitle: "Run critiques that improve work instead of defending it.",
    spine: [
      "What critique is for",
      "Preparing work for critique",
      "Giving useful feedback",
      "Receiving critique",
      "Facilitating a session",
      "Critique across disciplines",
    ],
    tags: ["communication", "leadership", "ux-research"],
  },

  /* ===================== PERSONAL DEVELOPMENT ===================== */
  {
    title: "Time Management for Complex Work",
    category: "personal-development",
    level: "BEGINNER",
    subtitle: "Planning, prioritisation and systems that survive a chaotic week.",
    spine: [
      "Why lists fail",
      "Capture and clarify",
      "Prioritisation",
      "Planning a week",
      "Handling interruptions",
      "Reviewing and adjusting",
    ],
    tags: ["productivity", "communication"],
  },
  {
    title: "Public Speaking for Technical Audiences",
    category: "personal-development",
    level: "INTERMEDIATE",
    subtitle: "Talks that hold attention and survive the question session.",
    spine: [
      "Structuring a talk",
      "Slides that support you",
      "Delivery and nerves",
      "Explaining complexity",
      "Handling questions",
      "Rehearsal and feedback",
    ],
    tags: ["communication", "writing", "leadership"],
  },
  {
    title: "Career Development for Engineers",
    category: "personal-development",
    level: "ALL_LEVELS",
    subtitle: "Levels, scope and choosing work that compounds.",
    spine: [
      "How levels actually work",
      "Scope and impact",
      "Choosing projects",
      "Visibility without self-promotion",
      "Mentors and sponsors",
      "Planning a move",
    ],
    tags: ["leadership", "negotiation", "hiring"],
  },

  /* ===================== PROJECT MANAGEMENT ===================== */
  {
    title: "Kanban and Flow Metrics",
    category: "project-management",
    level: "INTERMEDIATE",
    subtitle: "Limit work in progress and measure flow rather than velocity.",
    spine: [
      "Flow as the unit",
      "Visualising work",
      "Work in progress limits",
      "Cycle time and throughput",
      "Forecasting from flow",
      "Continuous improvement",
    ],
    tags: ["agile", "estimation", "analytics"],
  },
  {
    title: "Product Roadmapping",
    category: "project-management",
    level: "INTERMEDIATE",
    subtitle: "Roadmaps that communicate intent without promising dates you cannot keep.",
    spine: [
      "What a roadmap is for",
      "Outcomes over features",
      "Horizons and confidence",
      "Stakeholder alignment",
      "Revising a roadmap",
      "Communicating change",
    ],
    tags: ["stakeholders", "strategy", "communication"],
  },
  {
    title: "Programme Management Across Teams",
    category: "project-management",
    level: "ADVANCED",
    subtitle: "Dependencies, sequencing and delivery when no single team owns the outcome.",
    spine: [
      "Programmes versus projects",
      "Mapping dependencies",
      "Sequencing work",
      "Governance",
      "Reporting upward",
      "Closing a programme",
    ],
    tags: ["stakeholders", "risk", "estimation"],
  },

  /* ===================== LANGUAGES ===================== */
  {
    title: "Mandarin Chinese for Beginners",
    category: "languages",
    level: "BEGINNER",
    subtitle: "Tones, characters and building a foundation that does not collapse later.",
    spine: [
      "Tones and pinyin",
      "Basic sentence patterns",
      "Characters and radicals",
      "Numbers, dates and money",
      "Everyday conversation",
      "Building a study habit",
    ],
    tags: ["pronunciation", "vocabulary", "grammar"],
  },
  {
    title: "Portuguese for Travel and Work",
    category: "languages",
    level: "BEGINNER",
    subtitle: "Practical Portuguese for getting around and getting things done.",
    spine: [
      "Sounds and spelling",
      "Essential verbs",
      "Travel situations",
      "Workplace basics",
      "Past and future",
      "Keeping it up",
    ],
    tags: ["vocabulary", "pronunciation", "fluency"],
  },
  {
    title: "Academic Writing in English",
    category: "languages",
    level: "ADVANCED",
    subtitle: "Structure, citation and the register academic readers expect.",
    spine: [
      "Academic register",
      "Structuring an argument",
      "Literature and citation",
      "Precision and hedging",
      "Editing for clarity",
      "Responding to reviewers",
    ],
    tags: ["writing", "communication", "grammar"],
  },
  {
    title: "Italian Conversation Practice",
    category: "languages",
    level: "INTERMEDIATE",
    subtitle: "Move from understanding Italian to actually speaking it.",
    spine: [
      "From passive to active",
      "Everyday topics",
      "Past tenses in conversation",
      "Expressing opinion",
      "Idiom and register",
      "Sustaining longer exchanges",
    ],
    tags: ["fluency", "vocabulary", "pronunciation"],
  },
];
